#!/bin/bash

WD="$PWD"
cd "$( dirname "${BASH_SOURCE[0]}" )"
cabal sandbox init
cd hlit-types
cabal sandbox init --sandbox "../.cabal-sandbox"
for sub in hlit-tool hlit-diagrams-svg; do
    cd "../$sub"
    cabal sandbox init --sandbox "../.cabal-sandbox"
    cabal sandbox add-source ../hlit-types
done
cd "$WD"
